### PR TITLE
Figure update to figure-md

### PR DESCRIPTION
**Pull request by saadrahim**

### CODE REVIEW

**Review by Rmalavally — COMMENTED** [review]
@saadrahim Have we established file names for images? If we are referencing images by name rather than number, it can be prone to error. Especially with multiple versions and images. What is the process to ensure developers have used the correct image? How would documentation know for review purposes? Assume all images will be stored in the images folder.

**Comment by saadrahim** [comment]
> @saadrahim Have we established file names for images? If we are referencing images by name rather than number, it can be prone to error. Especially with multiple versions and images. What is the process to ensure developers have used the correct image? How would documentation know for review purposes? Assume all images will be stored in the images folder.

Yes, images need to use snake_case and not numbering. Some of the older image names need changing.

**Comment by Rmalavally** [comment]
Thanks, Saad. Snake_case is fine for files. 

We use camelCase for method names and variables and underscores for functions. Will the integrated linter bypass these cases? Does it require additional configuration? Is this documented in the contribution guide?

**Comment by Rmalavally** [comment]
Thanks, Saad. Sorry, I was not clear in my question. Will the linter identify the CamelCase as a typo? Can it be customized to bypass CamelCases? If not, we must manually correct all instances, which will be many.

**Comment by saadrahim** [comment]
There is no linting planned for camelcase checks at moment. If we do enable it, it will be for file names only.

**Pull request merged**
