### PR TITLE
2600 docker image support matrix rst 2 md

### PR DESCRIPTION
**Pull request by danpetreamd**
Here's my [proposal ](https://github.com/RadeonOpenCompute/ROCm/blob/2600-docker-image-support-matrix-rst-2-md/docs/release/docker_image_support_matrix.md)of what the [docker_image_support_matrix.rst](https://github.com/RadeonOpenCompute/ROCm/blob/roc-5.7.x/docs/release/docker_image_support_matrix.rst) file should look like if converted to GitHub Markdown per documentation guidelines.

### CODE REVIEW

**Comment by saadrahim** [comment]
My intention is to turn off the rst linter for now until we get reST linting to support sphinx-design extensions. My opinion is that reST version of this content is easier to navigate. ROCm documentation will likely use more reST in the future.

**Comment by danpetreamd** [comment]
[Supported formats](https://github.com/RadeonOpenCompute/ROCm/blob/roc-5.7.x/CONTRIBUTING.md#supported-formats)

I agree reST looks a lot better once converted to HTML.
It's just that IMO on GitHub reST can look substantially worse than GitHub Markdown.
This is such a case.

There might be another approach to displaying the same info in a more compact and markdown compatible fashion. Please give me a bit to make the changes as an example.

**Comment by danpetreamd** [comment]
Please take a look at the new [proposal](https://github.com/RadeonOpenCompute/ROCm/blob/2600-docker-image-support-matrix-rst-2-md/docs/release/docker_image_support_matrix.md).

Personally I think this looks better than the original reST. It is very compact and it looks great in text mode as well.
I used the reference mechanism in markdown to move all the links to the bottom of the file.
I made some compromises as well. In order to achieve such compactness I gave up on the tags and used just links which means that in order to get the tag the user would have to follow the link first. Not a biggie but we loose some convenience.

Thanks!

**Comment by danpetreamd** [comment]
I'm not sure what to do about the spelling check.
These are the actual words we need to use.

> Processing: docs/release/docker_image_support_matrix.md
Misspelled words:
<url-free> docs/release/docker_image_support_matrix.md
--------------------------------------------------------------------------------
```
OMPI
Tensorboard
centos
dev
pytorch
tensorflow
tf
ubuntu
```

**Comment by samjwu** [comment]
> I'm not sure what to do about the spelling check. These are the actual words we need to use.
> 
> > Processing: docs/release/docker_image_support_matrix.md
> > Misspelled words:
> >  docs/release/docker_image_support_matrix.md
> 
> ```
> OMPI
> Tensorboard
> centos
> dev
> pytorch
> tensorflow
> tf
> ubuntu
> ```

Spell checks are done against a default dictionary. We also have a custom wordlist at https://github.com/RadeonOpenCompute/rocm-docs-core/blob/develop/.wordlist.txt

You can make a PR to add any missing or new words.

Some other notes:

- word list is case sensitive. pytorch != PyTorch
- if it's a package name you can wrap it in tilde. spell check escapes code blocks. `centos`

**Comment by LisaDelaney** [comment]
Hi @danpetreamd, we've decided that rst will better serve our documentation goals going forward, so we will be converting all md files to rst over time. The md version/features we were using was increasingly dependent upon myst md and other workarounds, which render much worse than rst on GitHub. And, being md, it comes with the expectation that it will render nicely on GitHub whereas rst doesn't have such an expectation. If you have a look at the develop branch, you'll see the updates we've been making (you might be interested in https://github.com/RadeonOpenCompute/ROCm/blob/develop/CONTRIBUTING.md)

**Comment by danpetreamd** [comment]
Hi @LisaDelaney, thank you for the new guideline about contributions to the documentation. I only read the one on the [roc-5.7.x](https://github.com/RadeonOpenCompute/ROCm/blob/roc-5.7.x/CONTRIBUTING.md) branch which was recommending GitHub Markdown over RST. Had I seen the new guidelines earlier I might've saved myself some effort 😁.

IMO GitHub Markdown can strike a good balance between readability in the terminal and in GitHub/html, as shown by my version of the docker support matrix . But definitely RST is far superior in features.

Ultimately it is your decision, I recognize that. 👍

**Pull request closed without merging**
