### PR TITLE
Edited the quickstart guide for linux so all commands appear in a single place

### PR DESCRIPTION
**Pull request by abhimeda**
Edited the file and moved all commands to a singular console block that can be copy pasted into a terminal to install ROCm.

### CODE REVIEW

**Review by samjwu — COMMENTED** [review]
The explanations may be helpful for users installing (eg: the {rubric} section)

I think we should keep those as comments or something similar

**Comment by Rmalavally** [comment]
> The explanations may be helpful for users installing (eg: the {rubric} section)
> 
> I think we should keep those as comments or something similar

Thanks, Sam. 

My recommendation is to have QA review it before we merge the PR. @rkebichi

**Comment by rkebichi** [comment]
> > The explanations may be helpful for users installing (eg: the {rubric} section)
> > I think we should keep those as comments or something similar
> 
> Thanks, Sam.
> 
> My recommendation is to have QA review it before we merge the PR. @rkebichi

Hi @Rmalavally, I checked with Freddy from installation and packaging team and he said "testing it is good to ensure formatting do not cause issues". Please do the necessary to have this doc change tested. Thanks.

**Comment by abhimeda** [comment]
Could I receive an update with the testing? Is there anything I need to clarify or explain?

**Pull request closed without merging**
