### PR TITLE
update gpu-enabled-mpi

### PR DESCRIPTION
**Pull request by edgargabriel**
update the documentation to also include libfabric based network interconnects, not just UCX.

### CODE REVIEW

**Review by Rmalavally — DISMISSED** [review]
Nicely written. Thanks, @edgargabriel

**Comment by edgargabriel** [comment]
> Nicely written. Thanks, @edgargabriel

Thank you @Rmalavally , I appreciate it! Short question: do you know how I could deal with the spell check errors, there seem to be a few technical terms that the spell checker doesn't recognize

**Comment by Rmalavally** [comment]
> > Nicely written. Thanks, @edgargabriel
> 
> Thank you @Rmalavally , I appreciate it! Short question: do you know how I could deal with the spell check errors, there seem to be a few technical terms that the spell checker doesn't recognize

You will need to update the wordlist with the new technical terms. You can access wordlist.txt at 
https://github.com/RadeonOpenCompute/ROCm/blob/3f855e386c98bea274a5f10eed369e0a4cab748d/.wordlist.txt

You can also refer to Contributing.md for details on how to contribute to ROCm documentation.
https://github.com/RadeonOpenCompute/ROCm/blob/3f855e386c98bea274a5f10eed369e0a4cab748d/CONTRIBUTING.md

**Comment by edgargabriel** [comment]
Hm, well the update to the wordlist did fix the spell checker reported issues on the file that I modified, but it is now suddenly reporting spell checking errors from files that I didn't touch with this pr. Not sure what to do about that

**Comment by Rmalavally** [comment]
> Hm, well the update to the wordlist did fix the spell checker reported issues on the file that I modified, but it is now suddenly reporting spell checking errors from files that I didn't touch with this pr. Not sure what to do about that

Could you please share the errors you are getting?

**Comment by edgargabriel** [comment]
The errors come from two files:

```
> Processing: docs/conceptual/cmake-packages.rst
Misspelled words:
<url-free> docs/conceptual/cmake-packages.rst
--------------------------------------------------------------------------------
CLion
CMake's
CXX
IDEs
Intergration
MyApp
MyLib
MyProj
Nvidia
Wextra
amdclang
binaryDir
buildPresets
...
```

and 

```
> Processing: docs/conceptual/More-about-how-ROCm-uses-PCIe-Atomics.rst
Misspelled words:
<url-free> docs/conceptual/More-about-how-ROCm-uses-PCIe-Atomics.rst
--------------------------------------------------------------------------------
ATI
AtomicOp
AtomicOpCompletion
AtomicOps
AtomicsOp
AtomicsOps
Completers
DEVCAP
GenZ
IRQ
MMIO
MMIOH
MindShare
...
(many more)
```

**Comment by samjwu** [comment]
Some background: previously spellcheck only checked Markdown files. Recently we added RST, which had some spelling errors (eg: Intergration) and technical terms that are not in our wordlist.

We need to resolve these errors in a separate PR. No changes should be required on your end @edgargabriel

**Comment by edgargabriel** [comment]
@Rmalavally may I ask you to review in that case this pr again? Because I made a change to the pr after your review, your review has automatically been dismissed by the system. I would like to get this pr into the ROCm 6.0 release, it is based on a customer feedback/request

**Comment by Rmalavally** [comment]
> @Rmalavally may I ask you to review in that case this pr again? Because I made a change to the pr after your review, your review has automatically been dismissed by the system. I would like to get this pr into the ROCm 6.0 release, it is based on a customer feedback/request

Happy to help. Is this documentation update specific to customer requirements? Is it okay to make this content publicly available? Please confirm.

**Comment by edgargabriel** [comment]
> Happy to help. Is this documentation update specific to customer requirements? Is it okay to make this content publicly available? Please confirm.

yes,  the content of the pr is meant for public consumption. I sent in Teams the ticket that explains the details why this is necessary.

**Comment by Rmalavally** [comment]
> > Happy to help. Is this documentation update specific to customer requirements? Is it okay to make this content publicly available? Please confirm.
> 
> yes, the content of the pr is meant for public consumption. I sent in Teams the ticket that explains the details why this is necessary.

Thanks so much, Edgar. Appreciate your prompt response.

**Comment by LisaDelaney** [comment]
Hi @edgargabriel, the content is in academic style, so I'm going to rework it into a tech doc (active voice, present tense, etc). I'll submit a PR on this PR with the changes if that works for you.

**Comment by edgargabriel** [comment]
@LisaDelaney sounds good to me, thank you!

**Comment by LisaDelaney** [comment]
closing this PR in favor of https://github.com/RadeonOpenCompute/ROCm/pull/2655

**Pull request closed without merging**
