### PR TITLE
Added the table content in toc_yml file

### PR DESCRIPTION
**Pull request by urtiwari**
Please review the file.

### CODE REVIEW

**Review by samjwu — CHANGES_REQUESTED** [review]
The Spack introduction should go under either the Tutorial section or the How To section

**Comment by urtiwari** [comment]
@samjwu The document it self is under how-to and the document has a logical flow so I can't split it.

**Comment by samjwu** [comment]
> @samjwu The document it self is under how-to and the document has a logical flow so I can't split it.

image

I meant its position in the table of contents

**Comment by samjwu** [comment]
Preview of this change: https://advanced-micro-devices-demo--2526.com.readthedocs.build/en/2526/

**Review by samjwu — APPROVED** [review]

**Review by Rmalavally — APPROVED** [review]

**Pull request merged**
