### PR TITLE
Markdownify list of supported operating systems

### PR DESCRIPTION
**Pull request by Bengt**
This uses GitHub-flavored Markdown to create the table, which lists the supported operating systems. When compared to the former image, this helps with screen readers, search engine optimization and also with maintenance of this code base.

### CODE REVIEW

**Comment by icarus-sparry** [comment]
Good improvement.

**Comment by keryell** [comment]
Thanks!

**Comment by saadrahim** [comment]
Closing this PR as documentation is no longer contained in this repository.

**Comment by saadrahim** [comment]
At the moment documentation is not maintained in this repository or on github.com. A mechanism for public feedback for documentation is planned.

**Comment by Bengt** [comment]
I see. Thanks for the information. How is the process of providing feedback like this to the documentation if there is no mechanism currently in place?

**Comment by saadrahim** [comment]
If you take a look at https://docs.amd.com/bundle/ROCm-Release-Notes-v5.2/page/About_This_Document.html, there is a small feedback icon on the right side of the page. That is the current process to submit feedback.

**Comment by saadrahim** [comment]
As the change entered the documentation already, I will close this PR.

**Comment by Bengt** [comment]
Awesome. Thanks for the guidance, @saadrahim!

**Pull request closed without merging**
