### PR TITLE
Swati develop

### PR DESCRIPTION
**Pull request by SwRaw**
https://advanced-micro-devices-demo--2258.com.readthedocs.build/en/2258/understand/gpu_arch/mi200_performance_counters.html

### CODE REVIEW

**Comment by saadrahim** [comment]
@Maetveis is there a way good way to deal with the spell check words for the MI200 perf counter file?

**Comment by Rmalavally** [comment]
@samjwu Is there a way to make table creation easy? Creating tables manually is highly prone to error and inefficient. Please advise.

**Comment by samjwu** [comment]
> @samjwu Is there a way to make table creation easy? Creating tables manually is highly prone to error and inefficient. Please advise.

https://www.tablesgenerator.com/markdown_tables
This seems promising.

**Comment by Rmalavally** [comment]
We have used this before, but it renders incorrectly. Creating 20 tables manually in Markdown impacts productivity.

**Comment by SwRaw** [comment]
> @Maetveis is there a way good way to deal with the spell check words for the MI200 perf counter file?

Could you please let me know which words should be tagged as `word` to avoid spell-check and which should be added in the wordlist file? I thought that keywords that are in the code (any word that is not in the dictionary but used in the code or technical community) should be escaped from spell check.

**Comment by samjwu** [comment]
> We have used this before, but it renders incorrectly. Creating 20 tables manually in Markdown impacts productivity.

It looks like there was an error when using the table directive (`:::{table}`). 
I removed all references to the table directive to simplify the syntax and it's rendering nicely now: https://advanced-micro-devices-demo--2258.com.readthedocs.build/en/2258/understand/gpu_arch/mi200_performance_counters.html

> Could you please let me know which words should be tagged as word to avoid spell-check and which should be added in the wordlist file? I thought that keywords that are in the code (any word that is not in the dictionary but used in the code or technical community) should be escaped from spell check.

Words marked as code (surrounded by the tilde ` character) will not be checked by spell check. You can also surround text with three tildes to make a code block for multiple lines of code:

```
1
2
3
a
b
c
```

All other words will be checked.

**Comment by SwRaw** [comment]
> > We have used this before, but it renders incorrectly. Creating 20 tables manually in Markdown impacts productivity.
> 
> It looks like there was an error when using the table directive (`:::{table}`). I removed all references to the table directive to simplify the syntax and it's rendering nicely now: https://advanced-micro-devices-demo--2258.com.readthedocs.build/en/2258/understand/gpu_arch/mi200_performance_counters.html
> 
> > Could you please let me know which words should be tagged as word to avoid spell-check and which should be added in the wordlist file? I thought that keywords that are in the code (any word that is not in the dictionary but used in the code or technical community) should be escaped from spell check.
> 
> Words marked as code (surrounded by the tilde ` character) will not be checked by spell check. You can also surround text with three tildes to make a code block for multiple lines of code:
> 
> ```
> 1
> 2
> 3
> a
> b
> c
> ```
> 
> All other words will be checked.

@samjwu I am aware of this. I just wanted to know what category of words should be escaped from spell-check (using tilde) and what category should be added to the wordlist. There are coding conventions, nomenclatures, abbreviations etc., which are liable to fail spell-check. Should all be marked with tilde? So far, I have not been able to trace a pattern.

**Pull request merged**
