### PR TITLE
Compat-section-5.6

### PR DESCRIPTION
**Pull request by MathiasMagnus**
Update supported OS version and 3rd party framework versions.

_Note: I couldn't find the source for tested kernel/user-space combinations._

### CODE REVIEW

**Comment by Rmalavally** [comment]
We have previously worked closely with QA for tested and validated matrices. Please work with QA to ensure technical accuracy.

**Comment by radudiaconu0** [comment]
> We have previously worked closely with QA for tested and validated matrices. Please work with QA to ensure technical accuracy. 

Sorry I meant Windows support

**Comment by Rmalavally** [comment]
My apologies @radudiaconu0 . My comment was for the technical writer on our team @Naraenda.

**Comment by radudiaconu0** [comment]
> My apologies @radudiaconu0 . My comment was for the technical writer on our team @Naraenda. 
> 
> 

Oh my bad then

**Review by Rmalavally — CHANGES_REQUESTED** [review]
Please change 3rd party to Third-party Support Matrix.

**Comment by saadrahim** [comment]
superseded by new PR #2294

**Pull request closed without merging**
