### PR TITLE
remove dumplicated remote=roc-github

### PR DESCRIPTION
**Pull request by xuhuisheng**

### CODE REVIEW

**Comment by ROCmSupport** [comment]
Thanks @xuhuisheng for the patch.
We will check and merge it asap.

**Comment by xuhuisheng** [comment]
@ROCmSupport Thank you for responsing. Had update the path to latest content.

**Comment by rkothako** [comment]
Sure @xuhuisheng, we will check and update accordingly.

**Comment by rkothako** [comment]
Hi @xuhuisheng 
Patch has been merged now.
Thank you.

**Comment by rkothako** [comment]
Hi @xuhuisheng 
Request to close the ticket now.
Thank you.

**Pull request merged**
