### PR TITLE
Update Changelog and latest Release notes

### PR DESCRIPTION
**Pull request by samjwu**

### CODE REVIEW

**Review by Rmalavally — COMMENTED** [review]
@LisaDelaney Let's discuss if we must fix the redundancies in the changelog.  
@randyh62

**Comment by LisaDelaney** [comment]
> @LisaDelaney Let's discuss if we must fix the redundancies in the changelog. @randyh62

Sure: what redundancies are you referring to?

**Review by Rmalavally — COMMENTED** [review]
I am good with the team's decision, as @LisaDelaney is working on the edits. There is inconsistency in language and format. 
@samjwu

**Comment by saadrahim** [comment]
@samjwu can you rebuild the changelog based on what is in the develop branch? @LisaDelaney made many edits relevant for 6.0?

**Comment by samjwu** [comment]
> @samjwu can you rebuild the changelog based on what is in the develop branch? @LisaDelaney made many edits relevant for 6.0?

@saadrahim rebuilt the changelog

**Comment by samjwu** [comment]
> @samjwu can you rebuild the changelog based on what is in the develop branch? @LisaDelaney made many edits relevant for 6.0?

The script grabs updates from the release/rocm-rel-6.0 branch, not develop/master/amd-staging, etc.

**Review by LisaDelaney — APPROVED** [review]

**Pull request merged**
