### PR TITLE
Update using_gpu_sanitizer.md

### PR DESCRIPTION
**Pull request by searlmc1**
Update AMD supplied libs section

### CODE REVIEW

**Review by b-sumner — COMMENTED** [review]
Looks good to me!

**Review by Rmalavally — APPROVED** [review]

**Comment by Rmalavally** [comment]
Looks good, @searlmc1.  Thanks for your changes. We are still waiting to hear from Nirmal about specific meta packages in ASAN. We can confirm the content once we hear back from them.

**Comment by searlmc1** [comment]
> Looks good, @searlmc1. Thanks for your changes. We are still waiting to hear from Nirmal about specific meta packages in ASAN. We can confirm the content once we hear back from them.

Hi @Rmalavally - The PR improves what we have based on the info we have. I don't understand why you want to hold it pending Nirmal's additional info. That sounds like a follow-on patch once that additional info is available. 

Thanks

**Comment by Rmalavally** [comment]
@searlmc1 Sounds good. If we can get the information before the ROCm v5.7 release, we can incorporate it for additional clarity. If not, we can update the content in a point release. I believe the documentation is already available.

**Comment by searlmc1** [comment]
+ @saadrahim 

Hi @Rmalavally ,

- You approved the PR ( thank you ). Who is authorized to merge it?
- Why is merging limited to a set of authorized users?

Thanks much,

Mark

**Comment by Rmalavally** [comment]
> * @saadrahim
> 
> Hi @Rmalavally ,
> 
> * You approved the PR ( thank you ). Who is authorized to merge it?
> * Why is merging limited to a set of authorized users?
> 
> Thanks much,
> 
> Mark

Hi Mark, I think Saad is authorized to merge for now. I can only approve PRs after a review. 

Regards,
Roopa

**Comment by saadrahim** [comment]
> > * @saadrahim
> > 
> > Hi @Rmalavally ,
> > 
> > * You approved the PR ( thank you ). Who is authorized to merge it?
> > * Why is merging limited to a set of authorized users?
> > 
> > Thanks much,
> > Mark
> 
> Hi Mark, I think Saad is authorized to merge for now. I can only approve PRs after a review.
> 
> Regards, Roopa

All the code owners are authorized to merge.

**Comment by Rmalavally** [comment]
Thanks, @saadrahim. That's good to know. I cannot merge; it's dimmed out.

**Comment by Rmalavally** [comment]
> > > * @saadrahim
> > > 
> > > Hi @Rmalavally ,
> > > 
> > > * You approved the PR ( thank you ). Who is authorized to merge it?
> > > * Why is merging limited to a set of authorized users?
> > > 
> > > Thanks much,
> > > Mark
> > 
> > 
> > Hi Mark, I think Saad is authorized to merge for now. I can only approve PRs after a review.
> > Regards, Roopa
> 
> All the code owners are authorized to merge. That includes @Rmalavally amongst a few more people.

Here's what I see, @saadrahim 
Codeowner

**Pull request merged**
