### PR TITLE
RX 6700* doc fixes in windows_support.md 

### PR DESCRIPTION
**Pull request by YellowRoseCx**
Corrected the RX 6700 series LLVM target to "gfx1031" in windows_support.md

Changed name from "RX 6750" to "RX 6750 XT"

### CODE REVIEW

**Review by Naraenda — APPROVED** [review]
Looks good to me. Thanks!

@saadrahim Is targeting develop good or should we target the roc-5.6.x branch?

**Review by saadrahim — APPROVED** [review]

**Comment by YellowRoseCx** [comment]
Also changed the LLVM target of the RX 7600 from gfx1100 to gfx1102

**Comment by YellowRoseCx** [comment]
> Looks good to me. Thanks!
> 
> @saadrahim Is targeting develop good or should we target the roc-5.7.x branch?

Just let me know and I can change the target branch to the most suitable one

**Review by saadrahim — APPROVED** [review]

**Comment by saadrahim** [comment]
@Naraenda or @samjwu please take get this cherry-picked to roc-5.7.x

**Pull request merged**
