### PR TITLE
Release notes for ROCm 5.5.0

### PR DESCRIPTION
**Pull request by Naraenda**
- [x] Check that no other libraries updates are included in ROCm 5.5.0
- [ ] Check if the release notes are correct

### CODE REVIEW

**Comment by radudiaconu0** [comment]
i really hope you forogt to add it in the pull request

**Comment by Naraenda** [comment]
@saadrahim 
- Library changes are correct now. 
- Transcribed latest changes from the provided document.

Let me know if I missed anything 😄

**Comment by radudiaconu0** [comment]
> @saadrahim 
> - Library changes are correct now. 
> - Transcribed latest changes from the provided document.
> 
> Let me know if I missed anything 😄 

So no windows support.....

**Comment by Rmalavally** [comment]
@Naraenda Do you have access to Sharepoint? The latest version is uploaded on Sharepoint. The version you downloaded from my OneDrive is obsolete and inaccurate.

**Comment by Naraenda** [comment]
Blocked: awaiting final revision for release notes.

**Review by AtHeartEngineer — APPROVED** [review]

**Review by saadrahim — APPROVED** [review]

**Comment by radudiaconu0** [comment]
Where is RDNA 3 support??????????????? @saadrahim @Naraenda . We waited for nearly 3 months!!!!!!!!!!!!! No windows support and no RDNA 3 support????? Are u kidding me????

**Comment by LMC4S** [comment]
> Where is RDNA 3 support??????????????? @saadrahim @Naraenda . We waited for nearly 3 months!!!!!!!!!!!!! No windows support and no RDNA 3 support????? Are u kidding me????

Bro chill. Just sell your card and buy from another brand that works I guess.

**Pull request merged**
