### PR TITLE
Added reference to AMD lab notes

### PR DESCRIPTION
**Pull request by jychang48**
It would be great to also provide readers a pointer to the public AMD lab notes series

### CODE REVIEW

**Review by saadrahim — APPROVED** [review]
Looks good to me. 

Let's have this as the start of a fruitful collaboration.

**Comment by saadrahim** [comment]
@jychang48 can also provide the links to your blogs. Let's find a place to integrate those as well.

**Comment by jychang48** [comment]
@saadrahim sure, let me discuss with the team to see how we can best make this happen

**Comment by saadrahim** [comment]
> @saadrahim sure, let me discuss with the team to see how we can best make this happen

All I am thinking was to put in the links to the GPUOpen site.

**Pull request merged**
